title: lHello Github!!
author: lhori
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my learning github course. To learn how the yaml file works in github.
theme: minima
# social links
twitter_username: Berta_Ivy # DO NOT include the @ character, or else the build will fail!
github_username:  lhori # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
